/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <cstddef>
/* Header for class com_demo_dynamicjni_DynamicTest */

#ifndef _Included_com_demo_dynamicjni_DynamicTest
#define _Included_com_demo_dynamicjni_DynamicTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_demo_dynamicjni_DynamicTest
 * Method:    getInt
 * Signature: ()I
 */
/*JNIEXPORT jint JNICALL get_int
  (JNIEnv *, jobject);
*/
JNIEXPORT jint JNICALL addTwoNumber
  (JNIEnv *, jobject, jint, jint);


#ifdef __cplusplus
}
#endif
#endif
